services:
  backend:
    build: .
    container_name: real_estate_api
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: real_estate
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: